name: bekam
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6-246.0.dev <4.0.0'

dependencies:
  cloud_firestore: ^4.8.4
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.0
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.7
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_sign_in: ^6.1.4
  import_sorter: ^4.6.0
  json_annotation: ^4.8.1
  lottie: ^2.5.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.12

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/

  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/titillium/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/titillium/TitilliumWeb-Italic.ttf
        - asset: assets/fonts/titillium/TitilliumWeb-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/titillium/TitilliumWeb-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
