name: bekam
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6-246.0.dev <4.0.0'

dependencies:
  # In-app localization & translation with map data.  
  auto_route: ^7.8.4
   # discover the state of the network (WiFi & mobile/cellular) connectivity on Android and iOS.
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.2
  # load and cache network images. Can also be used with placeholder and error widgets.
  cached_network_image: ^3.3.0
  # Approximate how your Flutter app looks and performs on another device.
  device_preview: ^1.1.0
   #HTTP networking package
  dio: ^5.3.3
  #enabling authentication with firebase
  firebase_auth: ^4.14.0
  #Flutter plugin for Firebase Core, enabling connecting to multiple Firebase apps.
  firebase_core: ^2.22.0
  # state management package
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  #A flutter plugin for adapting screen and font size.Guaranteed to look good on different models  
  flutter_screenutil: ^5.9.0  
  # collection of Flutter grids layouts (staggered, masonry, quilted, woven, etc.).
  flutter_staggered_grid_view: ^0.7.0
  #An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^2.0.9
  # cubit state generator using source_gen 
  freezed: ^2.4.5
  #Annotations for the freezed code-generator.
  freezed_annotation: ^2.4.1
  # Dependency Injection helper
  get_it: ^7.6.4
  # Automatically organize your dart imports
  import_sorter: ^4.6.0
  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization.
  json_annotation: ^4.8.1
  # logs network calls in a pretty, easy to read format.
  pretty_dio_logger: ^1.3.1
  #webservice [http requests with dio] generator using source_gen 
  retrofit: ^4.0.3
  # reading and writing simple key-value pairs. Wraps NSUserDefaults on iOS and SharedPreferences on Android.
  shared_preferences: ^2.2.2
  #Customizable animated page indicator with a set of built-in effects.
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  #A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.6
  #A non-interactive HTML documentation generator for Dart source code
  dartdoc: any
  #Recommended lints for Flutter apps, packages, and plugins to encourage good coding practices.
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  #Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.7.1
  #generator using source_gen [we use it with cubit state generation]
  retrofit_generator: ^7.0.8

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onBoarding/
    - assets/svg/

  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSansMedium.ttf
          weight: 500
        - asset: assets/fonts/DMSansBold.ttf
          weight: 700
        - asset: assets/fonts/DMSansRegular.ttf
          weight: 400
