// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyfXy9U0oBg4-e8FtaGzruss3JTtYsdsw',
    appId: '1:994795731395:web:391d0920779e4d0771a576',
    messagingSenderId: '994795731395',
    projectId: 'bekam-2d852',
    authDomain: 'bekam-2d852.firebaseapp.com',
    storageBucket: 'bekam-2d852.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv1q9RbhX01A9DSvNU5c4L2-X0_br4JaM',
    appId: '1:994795731395:android:b55866fa7234ee1f71a576',
    messagingSenderId: '994795731395',
    projectId: 'bekam-2d852',
    storageBucket: 'bekam-2d852.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH8ryWKv-7-6nPCTHmVZoL0DlkyhVJq9c',
    appId: '1:994795731395:ios:47128326df2f92e271a576',
    messagingSenderId: '994795731395',
    projectId: 'bekam-2d852',
    storageBucket: 'bekam-2d852.appspot.com',
    iosClientId: '994795731395-0mncpfj1k1920l0101jdbem6r61eu9mc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bekam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH8ryWKv-7-6nPCTHmVZoL0DlkyhVJq9c',
    appId: '1:994795731395:ios:6bdd0bc9ed0f5f4471a576',
    messagingSenderId: '994795731395',
    projectId: 'bekam-2d852',
    storageBucket: 'bekam-2d852.appspot.com',
    iosClientId: '994795731395-d7nmk1s2ekdl3td7oh0bj0ibt0larjv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bekam.RunnerTests',
  );
}
